"""Processing pipeline assistance library."""
from proctools.bulk import (
    add_missing_fields,
    bulk_clean_all_whitespace,
    bulk_clean_whitespace,
    bulk_enforce_yn_values,
    bulk_make_values_lowercase,
    bulk_make_values_title_case,
    bulk_make_values_uppercase,
    bulk_replace_all_null_values,
    bulk_replace_null_values,
    bulk_update_values_by_function,
)
from proctools.communicate import (
    extract_email_addresses,
    send_email_smtp,
    send_links_email,
)
from proctools.filesystem import (
    NetUse,
    archive_folder,
    date_file_modified,
    extract_archive,
    folder_filepaths,
    get_flattened_path_string,
    same_file,
    update_file,
    update_replica_folder,
)
from proctools.manager import Batch, Job, Pipeline
from proctools.media import (
    IMAGE_FILE_EXTENSIONS,
    WORLD_FILE_EXTENSIONS,
    clean_pdf,
    clean_pdfs,
    convert_image_to_pdf,
    convert_image_to_thumbnail,
    convert_images_to_pdf,
    convert_images_to_thumbnails,
    merge_tiffs,
)
from proctools.metadata import Database, Dataset, Field
from proctools.misc import (
    access_odbc_string,
    last_date_of_day,
    log_entity_states,
    merge_common_collections,
    randomized,
    sql_server_odbc_string,
    time_elapsed,
    timestamp,
)
from proctools.portal import (
    delete_layer_features,
    get_item,
    get_layer,
    get_user,
    load_feature_layer,
    update_feature_attribute,
    upload_dataset_as_geodatabase,
)
from proctools.transfer import (
    dropbox_get_share_link,
    dropbox_upload_file,
    ftp_upload_file,
    secure_ftp_upload_file,
)
from proctools.value import (
    PUNCTUATION,
    TITLE_CASE_EXCEPTIONS,
    any_in_range,
    clean_whitespace,
    concatenate,
    date_as_datetime,
    datetime_from_string,
    enforce_yn,
    feature_key,
    feature_key_hash,
    is_numeric,
    leading_number_sort_key,
    make_lowercase,
    make_title_case,
    make_uppercase,
    make_zero_filled,
    max_value,
    min_value,
    parity,
    remove_diacritics,
    same_string_casefold,
    slugify,
    truncate_datetime,
)


__all__ = [
    # Bulk.
    "add_missing_fields",
    "bulk_clean_all_whitespace",
    "bulk_clean_whitespace",
    "bulk_enforce_yn_values",
    "bulk_make_values_lowercase",
    "bulk_make_values_title_case",
    "bulk_make_values_uppercase",
    "bulk_replace_all_null_values",
    "bulk_replace_null_values",
    "bulk_update_values_by_function",
    # Communicate.
    "extract_email_addresses",
    "send_email_smtp",
    "send_links_email",
    # Filesystem.
    "NetUse",
    "archive_folder",
    "date_file_modified",
    "extract_archive",
    "folder_filepaths",
    "get_flattened_path_string",
    "same_file",
    "update_file",
    "update_replica_folder",
    # Manager.
    "Batch",
    "Job",
    "Pipeline",
    # Media.
    "IMAGE_FILE_EXTENSIONS",
    "WORLD_FILE_EXTENSIONS",
    "clean_pdf",
    "clean_pdfs",
    "convert_image_to_pdf",
    "convert_images_to_pdf",
    "convert_image_to_thumbnail",
    "convert_images_to_thumbnails",
    "merge_tiffs",
    # Metadata.
    "Database",
    "Field",
    "Dataset",
    # Misc.
    "access_odbc_string",
    "last_date_of_day",
    "log_entity_states",
    "merge_common_collections",
    "randomized",
    "sql_server_odbc_string",
    "time_elapsed",
    "timestamp",
    # Portal.
    "delete_layer_features",
    "get_item",
    "get_layer",
    "get_user",
    "load_feature_layer",
    "update_feature_attribute",
    "upload_dataset_as_geodatabase",
    # Transfer.
    "dropbox_get_share_link",
    "dropbox_upload_file",
    "ftp_upload_file",
    "secure_ftp_upload_file",
    # Value.
    "PUNCTUATION",
    "TITLE_CASE_EXCEPTIONS",
    "any_in_range",
    "clean_whitespace",
    "concatenate",
    "date_as_datetime",
    "datetime_from_string",
    "enforce_yn",
    "feature_key",
    "feature_key_hash",
    "is_numeric",
    "leading_number_sort_key",
    "make_lowercase",
    "make_title_case",
    "make_uppercase",
    "make_zero_filled",
    "max_value",
    "min_value",
    "parity",
    "remove_diacritics",
    "same_string_casefold",
    "slugify",
    "truncate_datetime",
]
